services:
  frontend:
    build:
      context: ./frontend
    expose:
      - "5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - iis_network

  app:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - recommendations
      - search
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/iis
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_NEO4J_URI: bolt://neo4j:7687
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: password
    networks:
      - iis_network

  recommendations:
    build:
      context: ./recommendations
    expose:
      - "8001"
    depends_on:
      - neo4j
    networks:
      - iis_network

  search:
    build:
      context: search
    expose:
      - "8001"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - iis_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - app
      - recommendations
      - search
    networks:
      - iis_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8090:80"
    depends_on:
      - postgres
    networks:
      - iis_network

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: iis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iis_network

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - iis_network

  elasticsearch:
    image: elasticsearch:8.14.0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - iis_network

  kibana:
    image: kibana:8.14.0
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - iis_network

volumes:
  neo4j_data:
  postgres_data:
  elasticsearch_data:

networks:
  iis_network: