events {}

http {

    upstream frontend {
        server frontend:5173;
    }

    upstream backend {
        server app:8080;
    }

    upstream recommendations {
        server recommendations:8001;
    }

    upstream search {
        server search:8001;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location /api/recommendations/ {
            proxy_pass http://recommendations;
        }

        location /api/search/ {
            proxy_pass http://search;
        }

        location /api/ {
            proxy_pass http://backend;
        }
    }
}